FROM zamafhe/concrete-ml
WORKDIR /project
ADD ./input ./input
COPY ./requirements.txt ./requirements.txt
RUN python -m pip install -r requirements.txt
COPY ./train/model.py ./model.py
ENTRYPOINT /bin/bash